#!/bin/bash

source "creep/libboss/boss.sh"
source "creep/libcreep/utility.sh"

OP=$1
shift

case $OP in
	+|add)
		for f in "${@}"; do
			boss.add $f ${CREEP_BOSS_ADD_MODE:-submodule}
		done
	;;

	-|rm|remove)
		for f in "${@}"; do
			boss.remove $f
		done
	;;

	*)
		boss.logg "Executing the command: ${lcCmd}${OP} ${@}"
		boss.load
		boss.execute "$OP $@"
	;;
esac
