#!/bin/bash

source creep/libcreep/utility.sh
source creep/libcreep/creep.sh
source creep/libgit/git.sh

OP=$1
shift

case $OP in
	sm|submodule)
		source creep/libgit/submodule.sh $@
	;;

	*)
		git.log "Unknown command ${lcCmd}$OP${lcX}."
	;;
esac
