#!/bin/bash

source "creep/librunes/runes.sh"
source "creep/utility.sh"

OP=$1
shift

case $OP in
	keygen)
		source creep/librunes/keygen.sh
	;;

	secure)
		for f in "${@}"; do
			if flist.contains .creep/.runes $f; then
				runes.log "The $f file is already secured."
			else
				echo "$f" >> .creep/.runes
				runes.log "Secured $f."
			fi
		done
	;;

	unsecure)
		if flist.contains .creep/.runes $1; then
			flist.without .creep/.runes $1
			runes.log "Removed $1 from .creep/runes."
		else
			runes.log "The $1 file has never been secured."
		fi
	;;

	install-hooks)
		hook.install creep/librunes/.githooks/pre-commit .git/hooks/pre-commit $1
		hook.install creep/librunes/.githooks/post-checkout .git/hooks/post-checkout $1
	;;

	*)
		runes.log "Unknown command ${lcCmd}$OP"
	;;
esac
