#!/bin/bash

source creep/runes/runes.sh
source creep/creep.sh

runes.load $@

CHANGED=()

for RUNE in ${RUNES[@]}; do
	runes.encrypt $RUNE silent
	if git.diff $RUNE; then
		CHANGED+=("$RUNE")
	else
		runes.loggg "${lcRune}$RUNE${lcX} is up to date"
	fi
	runes.decrypt $RUNE silent
done;

if [[ ${#CHANGED[@]} > 0 ]]; then
	runes.encrypt.start

	for FILE in ${CHANGED[@]}; do
		runes.encrypt $FILE
		git.add $FILE
		runes.decrypt $FILE silent
	done

	runes.encrypt.finish;
fi
