#!/bin/bash

source creep/librunes/runes.sh
source creep/libcreep/creep.sh

runes.load $@
runes.decrypt.start

for FILE in ${RUNES[@]}; do
	FILE=${FILE#*  } # Trimming that leading "M  " status marker.
	if git.diff $FILE; then
		runes.loggg "The ${lcRune}${FILE}${lcX} has changed, skipping decryption."
	else
		runes.decrypt $FILE
	fi
done

runes.logg "\o/"
