#!/bin/bash

source creep/librunes/runes.sh
source creep/creep.sh

runes.load $@
runes.decrypt.start

for FILE in ${RUNES[@]}; do
	FILE=${FILE#*  } # Trimming that leading "M  " status marker.
	runes.decrypt $FILE
done

runes.logg "\o/"
